### PR TITLE
switch to klog

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan 

per promise in #5

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @coreydaley 

let's confirm you lgtm'ing a approved PR will allow for merge

**Comment by coreydaley** [comment]
@gabemontero looks like it needs a rebase, then i can lgtm it

**Comment by gabemontero** [comment]
yeah #8 updated the gomod stuff as well @coreydaley ... I'll rebase momentarily

**Comment by gabemontero** [comment]
ok update after rebase up @coreydaley

**Pull request merged**
