### PR TITLE
Clean up the Makefile and Dockerfiles

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
of course the driver yaml still points to my docker.io/gmontero @coreydaley ... my assumption was that was intentional until the new images actually exist on quay.io

**Comment by coreydaley** [comment]
> of course the driver yaml still points to my docker.io/gmontero @coreydaley ... my assumption was that was intentional until the new images actually exist on quay.io

Correct.

**Pull request merged**
