### PR TITLE
fix temp/development namespace reference

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @coreydaley

### CODE REVIEW

**Comment by gabemontero** [comment]
hmmmm @coreydaley @adambkaplan possibly looks like we need some more openshift/release  and prow dot connecting to get labelling, appove/lgtm working

I would have expected this PR to get approved out of the box since I created it

**Comment by coreydaley** [comment]
The lgtm that i just did added the label.  The release pr of mine hasn't merged yet either.

**Comment by gabemontero** [comment]
the PR just merged ... I'll give it a few to allow it to deploy all the bits to prow etc. and then close / reopen this PR, see what happens

**Comment by gabemontero** [comment]
well closing/reopening did not add the approve label @adambkaplan @coreydaley 

let's see if I can do it explicitly (albeit on my own PR) ... I *think* it is only lgtm that prevents that 

/approve

**Comment by gabemontero** [comment]
doesn't look like it ... @adambkaplan you were able to apply the approve label with the first PR ... can you do that here and we can see if this at least merges without the green button ?

**Comment by coreydaley** [comment]
/retest

I feel like CI is having issues today in general.

**Pull request merged**
